
VERSION = 2009
PATCHLEVEL = 08
SUBLEVEL =
EXTRAVERSION =
ifneq "$(SUBLEVEL)" ""
U_BOOT_VERSION = $(VERSION).$(PATCHLEVEL).$(SUBLEVEL)$(EXTRAVERSION)
else
U_BOOT_VERSION = $(VERSION).$(PATCHLEVEL)$(EXTRAVERSION)
endif
TIMESTAMP_FILE = $(obj)include/timestamp_autogenerated.h
VERSION_FILE = $(obj)include/version_autogenerated.h

HOSTARCH := x86_64
HOSTOS := linux
SHELL := /bin/bash
export HOSTARCH HOSTOS SHELL

OBJTREE		:= $(CURDIR)
SRCTREE		:= $(CURDIR)
TOPDIR		:= $(SRCTREE)
LNDIR		:= $(OBJTREE)
export	TOPDIR SRCTREE OBJTREE

obj :=
src :=
export obj src

ARCH   = arm
CPU    = cortexa9
BOARD  = omni
VENDOR = freescale
SOC    = mx6
export ARCH CPU BOARD VENDER SOC

include $(TOPDIR)/config.mk

BOOT_START = boot/start.o
BOOT_START := $(addprefix $(obj),$(BOOT_START))

BOOT_DCD = boot/dcd.bin
BOOT_DCD := $(addprefix $(obj),$(BOOT_DCD))

TARGET = imx6q

OBJS += $(BOOT_START) $(BOOT_DCD)

LIBS += board/lib$(BOARD).a

all: $(TARGET)
	echo "BOOT_START =" ${BOOT_START}
	echo "LDFLAGS =" ${LDFLAGS}

$(TARGET): $(OBJS) $(LIBS) $(LDSCRIPT)
	$(LD) $(LDFLAGS) $(BOOT_START) --start-group $(LIBS) --end-group -Map imx6q.map -o $@

$(LDSCRIPT): omni.lds
	$(CPP) $(CPPFLAGS) $(LDPPFLAGS) -ansi -D__ASSEMBLY__ -P - <$^ > $@

$(LIBS):depend
	$(MAKE) -C $(dir $(subst $(obj),,$@))

$(OBJS):depend
	$(MAKE) -C $(dir $(subst $(obj),,$@))

depend:

clean:
	@find $(OBJTREE) -type f \
		\( -name 'core' -o -name '*.bak' -o -name '*~' -o -name '*.map' \
		-o -name '*.o'	-o -name '*.a' -o -name '*.exe' -o -name '*.s'	\) -print \
		| xargs rm -f
	@find $(OBJTREE) -type f \( -name .depend \
		-o -name '*.srec' -o -name '*.bin' -o -name usb_downloader \) \
		-print0 \
		| xargs -0 rm -f
	@rm $(TARGET) $(LDSCRIPT)

