
VERSION = 2009
PATCHLEVEL = 08
SUBLEVEL =
EXTRAVERSION =
ifneq "$(SUBLEVEL)" ""
U_BOOT_VERSION = $(VERSION).$(PATCHLEVEL).$(SUBLEVEL)$(EXTRAVERSION)
else
U_BOOT_VERSION = $(VERSION).$(PATCHLEVEL)$(EXTRAVERSION)
endif
TIMESTAMP_FILE = $(obj)include/timestamp_autogenerated.h
VERSION_FILE = $(obj)include/version_autogenerated.h

HOSTARCH := x86_64
HOSTOS := linux
SHELL := /bin/bash
export HOSTARCH HOSTOS SHELL

OBJTREE		:= $(CURDIR)
SRCTREE		:= $(CURDIR)
TOPDIR		:= $(SRCTREE)
LNDIR		:= $(OBJTREE)
export	TOPDIR SRCTREE OBJTREE

obj :=
src :=
export obj src

ARCH   = arm
CPU    = cortexa9
BOARD  = omni
VENDOR = freescale
SOC    = mx6
export ARCH CPU BOARD VENDER SOC

include $(TOPDIR)/config.mk

LIBBOARD = board/$(BOARDDIR)/lib$(BOARD).a
LIBBOARD := $(addprefix $(obj),$(LIBBOARD))


all: $(LIBBOARD)
	echo "LIBBOARD =" ${LIBBOARD}


$(LIBBOARD):depend
	$(MAKE) -C $(dir $(subst $(obj),,$@))
	mv $(dir $(subst $(obj),,$@))/flash_header.s .

depend:

clean:
	@find $(OBJTREE) -type f \
		\( -name 'core' -o -name '*.bak' -o -name '*~' \
		-o -name '*.o'	-o -name '*.a' -o -name '*.exe'	\) -print \
		| xargs rm -f
	@find $(OBJTREE) -type f \( -name .depend \
		-o -name '*.srec' -o -name '*.bin' -o -name u-boot.img \) \
		-print0 \
		| xargs -0 rm -f

